spring:
  application:
    name: RESTful AppService with SrpingMVC, JPA, and SpringBoot
  datasource:
    url: jdbc:mysql://localhost:3306/sakila
    username: root
    password: Dev@Root@mi#!L0ve
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumpoolsize: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
  logging:
    file:
      name: /Coding/Logging/${spring.application.name}/log
